const buenosAires = {
    titulo: 'Descubre Buenos Aires, Capital de Argentina',
    subtitulo: 'Sumérgete en la historia, cultura y belleza de esta vibrante ciudad',
    parrafo: "Bienvenidos a Buenos Aires, una ciudad fascinante que mezcla la herencia europea con una energía única latinoamericana. Ubicada en la costa este de Argentina, esta capital dinámica es conocida por su arquitectura histórica, sus animados barrios, y una escena cultural vibrante. <br> <br> Nuestro recorrido comienza en el histórico barrio de San Telmo, donde las calles empedradas y los edificios coloniales crean una atmósfera nostálgica. Aquí podrás disfrutar de mercados de antigüedades, espectáculos de tango al aire libre y bares tradicionales. <br> <br> La Plaza de Mayo, en el centro de la ciudad, es otro sitio emblemático rodeado de importantes edificios históricos como la Casa Rosada, sede presidencial, y la Catedral Metropolitana. A pocos pasos, la famosa Avenida 9 de Julio es una de las más anchas del mundo y cuenta con el icónico Obelisco. <br> <br> Recoleta es un barrio imperdible, donde se encuentra el Cementerio de la Recoleta, conocido por sus imponentes mausoleos y estatuas. Cerca, el Museo Nacional de Bellas Artes ofrece una impresionante colección de obras argentinas e internacionales. <br> <br> Si buscas un ambiente moderno, Puerto Madero es el barrio ideal, con sus rascacielos, restaurantes de lujo y el famoso Puente de la Mujer. <br> <br> En resumen, Buenos Aires es una ciudad que te atrapará con su encanto, su pasión por el tango, y una oferta gastronómica deliciosa que incluye desde asados hasta empanadas. ¡Descubre la magia de Buenos Aires!",
    imagen: "imagenes-ciudades/buenosaires.jpg",
};

const roma = {
    titulo: 'Roma: La Ciudad Eterna',
    subtitulo: 'Explora la grandeza histórica, el arte y la cultura de la capital italiana',
    parrafo: "Bienvenidos a Roma, una ciudad llena de historia y maravillas arquitectónicas que te transportarán a través de los siglos. Conocida como la Ciudad Eterna, Roma es el hogar de una riqueza inigualable de monumentos antiguos, arte renacentista y una cultura vibrante que te cautivará desde el primer momento. <br> <br> Nuestro recorrido por Roma comienza en el Coliseo, el icónico anfiteatro que te sorprenderá con su imponente estructura y su historia. Desde las batallas de gladiadores hasta grandes espectáculos, este símbolo de Roma te sumergirá en el pasado. <br> <br> A pocos pasos, encontrarás el Foro Romano, el centro de la antigua vida política y social. Recorre sus ruinas y siente la grandeza de los templos, arcos y basílicas que aún permanecen en pie. <br> <br> Continuando nuestro recorrido, llegamos a la Ciudad del Vaticano, el corazón espiritual del catolicismo. La Basílica de San Pedro, con su magnífica cúpula diseñada por Miguel Ángel, y los Museos Vaticanos, hogar de la famosa Capilla Sixtina, son paradas obligadas para los amantes del arte y la historia. <br> <br> La Fontana di Trevi es otro de los sitios más encantadores de Roma. Lanza una moneda en sus aguas para asegurarte de que regresarás a la ciudad. <br> <br> En el encantador barrio de Trastevere, descubre el lado bohemio de Roma con sus calles empedradas, bares acogedores y restaurantes que ofrecen la auténtica cocina romana. <br> <br> En resumen, Roma es una ciudad que combina lo antiguo y lo moderno de una forma única. ¡Prepárate para explorar la historia, el arte y el romance que la Ciudad Eterna tiene para ofrecer!",
    imagen: "imagenes-ciudades/roma.jpg"
};

const miami = {
    titulo: 'Explora Miami, La Puerta de las Américas',
    subtitulo: 'Descubre las playas, la cultura y la vida nocturna de esta ciudad vibrante',
    parrafo: "Bienvenidos a Miami, una ciudad que brilla por su diversidad cultural y su ambiente tropical. Situada en el sur de Florida, Miami es un destino de sol, playa, y un crisol de culturas latinas. <br> <br> El recorrido comienza en South Beach, famosa por su arena blanca, sus aguas cristalinas y la icónica arquitectura art déco a lo largo de Ocean Drive. Aquí podrás disfrutar del sol, pasear entre restaurantes y boutiques exclusivas, y vivir la animada vida nocturna. <br> <br> El barrio de Little Havana es el corazón cultural latino de Miami. Calle Ocho, su calle principal, está llena de murales, tiendas y cafés que celebran la herencia cubana de la ciudad. Disfruta de un café cubano o de un sándwich cubano auténtico mientras exploras la zona. <br> <br> Para los amantes del arte, el barrio de Wynwood es un imperdible. Sus coloridos murales y galerías ofrecen una experiencia visual única, especialmente en el Wynwood Walls, una galería al aire libre con obras de artistas internacionales. <br> <br> En resumen, Miami es una ciudad donde puedes disfrutar de una mezcla única de cultura, arte y playa, y vivir experiencias que van desde lo relajado a lo vibrante. ¡Explora Miami y déjate llevar por su energía tropical!",
    imagen: "imagenes-ciudades/miami.jpg"
};

const newYork = {
    titulo: 'Nueva York: La Ciudad que Nunca Duerme',
    subtitulo: 'Descubre la energía, los rascacielos y la diversidad de la Gran Manzana',
    parrafo: "Bienvenidos a Nueva York, una ciudad que late con energía y diversidad, donde cada barrio tiene su propio carácter y encanto. Conocida como la Ciudad que Nunca Duerme, Nueva York es el hogar de famosos rascacielos, museos de clase mundial y una vida urbana que te cautivará. <br> <br> Nuestro recorrido por Nueva York comienza en el corazón de Manhattan, con el emblemático Times Square. Rodeado de luces brillantes, teatros y tiendas, Times Square es el centro vibrante de la ciudad y el lugar perfecto para experimentar su energía. <br> <br> La Estatua de la Libertad, uno de los símbolos más icónicos de los Estados Unidos, es una visita obligada. Tómate un ferry para admirar esta figura histórica y disfrutar de vistas impresionantes de la ciudad desde el puerto. <br> <br> Central Park, el enorme oasis urbano de Nueva York, ofrece un respiro de la vida agitada de la ciudad. Pasea por sus senderos, visita el Zoológico de Central Park o disfruta de un picnic rodeado de naturaleza en medio de Manhattan. <br> <br> Para los amantes del arte, el Museo Metropolitano de Arte (Met) y el Museo de Arte Moderno (MoMA) albergan colecciones de arte de renombre mundial. <br> <br> Cruza el Puente de Brooklyn para descubrir Brooklyn, un barrio con un carácter único. Desde el Parque del Puente de Brooklyn, podrás disfrutar de una vista panorámica del skyline de Manhattan. <br> <br> En resumen, Nueva York es una ciudad que ofrece una combinación única de cultura, historia y modernidad. Cada rincón de la ciudad tiene algo especial que mostrar, desde sus rascacielos hasta sus barrios encantadores. ¡Descubre Nueva York y déjate llevar por la magia de la Gran Manzana!",
    imagen: "imagenes-ciudades/newyork.jpg"
};

export {buenosAires, roma, miami, newYork};
